---


- include_tasks: "{{ ansible_distribution }}-install.yml"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS"
  tags:
    - install

- name: "create /etc/ansible_install_git_{{ git_version }}"
  command: "touch /etc/ansible_install_git_{{ git_version }}"
  args:
    creates: "/etc/ansible_install_git_{{ git_version }}"
